Fix for multiple word crud command
Laravel-Backpack/Generators pull request #114
Opened 2021-05-23 23:03 UTC by promatik

Until now doing something like;

`php artisan backpack:crud ...`
`product_category` renders `Route::crud('product_category', 'Product_categoryCrudController');`
`product-category` renders `Route::crud('product-category', 'Product-categoryCrudController');`
`productCategory` renders `Route::crud('productcategory', 'ProductCategoryCrudController');`

Also, the controller entity names were wrong.
```CRUD::setEntityNameStrings('productcategory', 'product_categories');```

--- 

This PR allows devs to use any format, either kebab-case, snake_case or Title Case.

`php artisan backpack:crud ...`
`product_category`, `product-category`, `productCategory`

It will always render what is expected.

`routes/custom.php`
```php
Route::crud('product-category', 'ProductCategoryCrudController');
```
`sidebar_content.blade.php`
```html
<li class='nav-item'><a class='nav-link' href='{{ backpack_url('product-category') }}'>
    <i class='nav-icon la la-question'></i> Product Categories</a>
</li>
```
`ProductCategoryCrudController.php`
```php
public function setup()
{
    CRUD::setModel(\App\Models\ProductCategory::class);
    CRUD::setRoute(config('backpack.base.route_prefix') . '/product-category');
    CRUD::setEntityNameStrings('Product Category', 'Product Categories');
}
```

2021-05-24 17:39 UTC, tabacitu commented
I LOVE THIS. Thanks @promatik !

2021-05-26 09:28 UTC, pxpm approved these changes
thanks @promatik 

I tested with: `product_category-test`, `ProDucTape`.

It just works!

2021-05-26 17:19 UTC, tabacitu requested changes
Looks like this is now capitalizing the first letter of a string, that before was uncapitalized. You can see that in the Add button on the List Operation.

Before:
![Screenshot 2021-05-26 at 20 17 30](https://user-images.githubusercontent.com/1032474/119703721-81930a80-be5f-11eb-90b0-1c7d74f89aa5.png)

After:
![Screenshot 2021-05-26 at 20 18 31](https://user-images.githubusercontent.com/1032474/119703765-8fe12680-be5f-11eb-9179-54f9b6e4e693.png)

It shouldn't be "Add Song", it should be "Add song" as it were before.

2021-06-17 07:29 UTC, promatik commented
@tabacitu it's fixed 🙌

![image](https://user-images.githubusercontent.com/1838187/122351115-bddcf680-cf45-11eb-8e93-dd686b57789d.png)

2021-06-22 12:11 UTC, pxpm commented
ping @tabacitu

2021-06-22 14:35 UTC, tabacitu commented
Tested, works great! Thanks @promatik !

2021-06-22 14:35 UTC, merged

2021-06-22 14:38 UTC, tabacitu commented
Tagged as 3.1.9 - https://github.com/Laravel-Backpack/Generators/releases/tag/v3.1.9