Command to create a new page
Laravel-Backpack/Generators pull request #140
Opened 2022-08-22 22:07 UTC by promatik

Fixes #138.

![image](https://user-images.githubusercontent.com/1838187/186026031-8b157a23-937c-4f16-b93f-eed535a7469c.png)

## WHY

### AFTER - What is happening after this PR?

Developers can run;

```cmd
php artisan backpack:page status
```
```cmd
php artisan backpack:page portugal --view-path=status --layout=blank
```

This will also work (thanks to @pxpm suggestion);
```cmd
php artisan backpack:page status.romania
```

<img width="790" alt="image" src="https://user-images.githubusercontent.com/1838187/186027013-31466cf1-69a1-4a6b-a435-5b6c88215c78.png">

`--view-path` defaults to `admin`, but devs are free to change it.
`--layout` also defaults to `blank`.
Later we may add `--controller-path`.

2022-08-23 15:55 UTC, tabacitu commented on src/Console/stubs/page.stub
> +    <p>To add logic to it, go to <code>{{ $controller }}</code> to edit the controller.</p>
```suggestion
    <p>Go to <code>{{ $page }}</code> to edit this view or <code>{{ $controller }}</code> to edit the controller.</p>
```

2022-08-23 16:03 UTC, tabacitu requested changes

2022-08-23 16:03 UTC, tabacitu commented on src/Console/Commands/PageBackpackCommand.php
> +    protected $signature = 'backpack:page {name}
What format will we require for this argument?
- I tried `Custom` - everything was generated fine
- I tried `MakersList` - the view name was `MarkersList` which... I didn't like, and the menu item was `Markerslist` which I didn't like either

It's ok to only support one format, that will help us generate proper names for everything... but... what would a good one be? `PascalCase` or `snake-case`?

2022-08-23 16:03 UTC, tabacitu commented
I freaking love this! Well done @promatik ! I have a few suggestions above.

2022-08-30 22:50 UTC, promatik commented on src/Console/stubs/page-controller.stub
> +class DummyClassController extends BaseController
Yeah, don't know where I found this one 🤦

2022-08-31 13:26 UTC, tabacitu requested changes
I love it! The generated pages work like a freaking charm - well done @promatik !

Nitpicking, but I noticed a few weird things in my console:

(1) the first two filepaths are blue, the last two are not:
<img width="900" alt="CleanShot 2022-08-31 at 16 24 40@2x" src="https://user-images.githubusercontent.com/1032474/187688988-eebda386-79e9-4558-b6eb-6aeabe66fc9a.png">

(2) the last path (sidebar entry) also has the dots underlined, when I hover it with Control pressed, so it won't open:
<img width="906" alt="CleanShot 2022-08-31 at 16 25 28@2x" src="https://user-images.githubusercontent.com/1032474/187689232-400634c2-9d88-4e26-acaa-69b775e9ba65.png">

After these final two... this is ready to go! Can't wait!

2022-08-31 15:02 UTC, pxpm commented
In your last screenshot it's also missing a `p` it displays: `.blade.ph` 👍

2022-09-01 00:46 UTC, promatik commented
@tabacitu sorry, forgot about pushing the changes to CRUD 😅
https://github.com/Laravel-Backpack/CRUD/pull/4631

Regarding the missing `p` in the file, that is related with the size of the command line, witch is also related with the `str_repeat` error, I will fix it in CRUD asap 👌

2022-09-01 07:09 UTC, merged