Create a php artisan backpack:button command
Laravel-Backpack/Generators pull request #141
Opened 2022-08-27 09:28 UTC by karandatwani92

New Feature:
What I did:
Created an operation, had no way to create a custom button really quick (with a stub).

What happens:
Run php artisan backpack:button email and it would create the button for me.

2022-08-30 07:31 UTC, tabacitu requested changes
Excellent. Great job @karandatwani92 . Please see my suggestions here - other than that, very happy with this. Eager to merge it!

2022-08-30 07:31 UTC, tabacitu commented on src/Console/stubs/button.stub
> +  <a href="{{ url($crud->route.'/'.$entry->getKey().'/dummy') }}" class="btn btn-sm btn-link text-capitalize"><i class="la la-envelope"></i> dummy</a>
My result for running `php artisan backpack:button moderate` was:

```php
@if ($crud->hasAccess('moderate'))
  <a href="{{ url($crud->route.'/'.$entry->getKey().'/moderate') }}" class="btn btn-sm btn-link text-capitalize"><i class="la la-envelope"></i> moderate</a>
@endif
```

I would expect it to be:
```php
@if ($crud->hasAccess('moderate'))
  <a href="{{ url($crud->route.'/'.$entry->getKey().'/moderate') }}" class="btn btn-sm btn-link text-capitalize"><i class="la la-envelope"></i> moderate</a>
@endif
```

With the differences being:
- [ ] using `la la-question` as the default icon (as we do for sidebar items)
- [ ] the first letter of the text inside the button being capitalized

2022-08-30 07:31 UTC, tabacitu commented on src/Console/Commands/ButtonBackpackCommand.php
> +
I don't know if this suggestion actually fixes what I said... it's just what stood out to me.

```suggestion
        $stub = str_replace('dummy', $name, $stub);
        $stub = str_replace('Dummy', ucfirst($name), $stub);
        
```

2022-08-30 07:31 UTC, tabacitu commented on src/Console/stubs/button.stub
> +  <a href="{{ url($crud->route.'/'.$entry->getKey().'/dummy') }}" class="btn btn-sm btn-link text-capitalize"><i class="la la-envelope"></i> dummy</a>
So maybe we do...

```suggestion
  <a href="{{ url($crud->route.'/'.$entry->getKey().'/dummy') }}" class="btn btn-sm btn-link text-capitalize"><i class="la la-question"></i> Dummy</a>
```

2022-08-30 07:31 UTC, tabacitu commented on src/Console/Commands/ButtonBackpackCommand.php
> +    protected $description = 'Generate a backpack templated button';
```suggestion
    protected $description = 'Generate a Backpack button';
```

2022-08-30 07:42 UTC, tabacitu commented
Also, please remember to also add docs for this new feature 🎉
- [ ] edit the README.md file, so we have it there too;
- [ ] create a different PR to change the docs repo, to use this new command ([this file here](https://github.com/Laravel-Backpack/Docs/blob/master/5.x/crud-buttons.md));

It's perfect the way we did it. First we build the feature. Then after the feature is approved/final (or almost final) we can add docs too. Otherwise, if we write the docs too soon, if the feature changes than the docs need changing too.

Let's do this @karandatwani92 ! 💪

2022-08-30 13:04 UTC, karandatwani92 commented on src/Console/stubs/button.stub
> +  <a href="{{ url($crud->route.'/'.$entry->getKey().'/dummy') }}" class="btn btn-sm btn-link text-capitalize"><i class="la la-envelope"></i> dummy</a>
> So maybe we do...

To capitalize the first letter, I used text-capitalize CSS class. Does the same thing in a simpler way. Should I change it ?

2022-09-06 12:34 UTC, karandatwani92 commented
> Also, please remember to also add docs for this new feature 🎉
> 
> * [x]  edit the README.md file, so we have it there too;
> * [ ]  create a different PR to change the docs repo, to use this new command ([this file here](https://github.com/Laravel-Backpack/Docs/blob/master/5.x/crud-buttons.md));
> * [ ]  make the output pretty like Antonio did it in `php artisan backpack:page` - [Command to create a new page #140](https://github.com/Laravel-Backpack/Generators/pull/140)
> 
> It's perfect the way we did it. First we build the feature. Then after the feature is approved/final (or almost final) we can add docs too. Otherwise, if we write the docs too soon, if the feature changes than the docs need changing too.
> 
> Let's do this @karandatwani92 ! 💪



> Also, please remember to also add docs for this new feature 🎉
> 
> * [x]  edit the README.md file, so we have it there too;
> * [ ]  create a different PR to change the docs repo, to use this new command ([this file here](https://github.com/Laravel-Backpack/Docs/blob/master/5.x/crud-buttons.md));
> * [ ]  make the output pretty like Antonio did it in `php artisan backpack:page` - [Command to create a new page #140](https://github.com/Laravel-Backpack/Generators/pull/140)
> 
> It's perfect the way we did it. First we build the feature. Then after the feature is approved/final (or almost final) we can add docs too. Otherwise, if we write the docs too soon, if the feature changes than the docs need changing too.
> 
> Let's do this @karandatwani92 ! 💪



> Also, please remember to also add docs for this new feature 🎉
> 
> * [x]  edit the README.md file, so we have it there too;
> * [ ]  create a different PR to change the docs repo, to use this new command ([this file here](https://github.com/Laravel-Backpack/Docs/blob/master/5.x/crud-buttons.md));
> * [ ]  make the output pretty like Antonio did it in `php artisan backpack:page` - [Command to create a new page #140](https://github.com/Laravel-Backpack/Generators/pull/140)
> 
> It's perfect the way we did it. First we build the feature. Then after the feature is approved/final (or almost final) we can add docs too. Otherwise, if we write the docs too soon, if the feature changes than the docs need changing too.
> 
> Let's do this @karandatwani92 ! 💪



> Also, please remember to also add docs for this new feature 🎉
> 
> * [x]  edit the README.md file, so we have it there too;
> * [ ]  create a different PR to change the docs repo, to use this new command ([this file here](https://github.com/Laravel-Backpack/Docs/blob/master/5.x/crud-buttons.md));
> * [ ]  make the output pretty like Antonio did it in `php artisan backpack:page` - [Command to create a new page #140](https://github.com/Laravel-Backpack/Generators/pull/140)
> 
> It's perfect the way we did it. First we build the feature. Then after the feature is approved/final (or almost final) we can add docs too. Otherwise, if we write the docs too soon, if the feature changes than the docs need changing too.
> 
> Let's do this @karandatwani92 ! 💪

#[](url)

> * R to c



> Also, please remember to also add docs for this new feature 🎉
> 
> * [x]  edit the README.md file, so we have it there too;
> * [ ]  create a different PR to change the docs repo, to use this new command ([this file here](https://github.com/Laravel-Backpack/Docs/blob/master/5.x/crud-buttons.md));
> * [ ]  make the output pretty like Antonio did it in `php artisan backpack:page` - [Command to create a new page #140](https://github.com/Laravel-Backpack/Generators/pull/140)
> 
> It's perfect the way we did it. First we build the feature. Then after the feature is approved/final (or almost final) we can add docs too. Otherwise, if we write the docs too soon, if the feature changes than the docs need changing too.
> 
> Let's do this @karandatwani92 ! 💪

@tabacitu Done! Please check

2022-09-06 12:35 UTC, karandatwani92 commented
@tabacitu Done! Please check

2022-09-06 12:35 UTC, tabacitu commented on src/Console/Commands/ButtonBackpackCommand.php
> +        $path = $this->getPath($name);
I see the output path is absolute (for my system) so it's not clickable:

<img width="1141" alt="CleanShot 2022-09-06 at 15 34 39@2x" src="https://user-images.githubusercontent.com/1032474/188636392-be629e01-d17f-439d-b2aa-c7610074252b.png">

The other commands, where the paths ARE clickable, are relative to the project folder, so `resources/views/...`

2022-09-06 12:38 UTC, tabacitu commented on src/Console/Commands/ButtonBackpackCommand.php
> +        $path = $this->getPath($name);
Please check how Antonio does it in the other commands - the output should be similar here, so that it's clickable.

2022-09-06 12:47 UTC, karandatwani92 commented on src/Console/Commands/ButtonBackpackCommand.php
> +        $path = $this->getPath($name);
@tabacitu now it's clickable

2022-09-08 09:03 UTC, merged

2022-09-08 09:04 UTC, tabacitu commented
Excellent! Good job @karandatwani92 👏👏👏 
Let's work towards the other PRs, to be as good as this one.

Congrats on your first merged PR here 😀🎉