Added `validation` option to `backpack:crud` command
Laravel-Backpack/Generators pull request #143
Opened 2022-09-05 00:47 UTC by promatik

Fix for https://github.com/Laravel-Backpack/Generators/issues/137

**This PR requires both;**;
- https://github.com/Laravel-Backpack/CRUD/pull/4646
- ...

This will accept `validation` option on `backpack:crud` command, or interactively ask for it.

![image](https://user-images.githubusercontent.com/1838187/188340142-fbf29a0f-7586-4e8e-8caf-5a49dd5e69c4.png)

![image](https://user-images.githubusercontent.com/1838187/188340151-63e3f731-03bf-4229-b122-50850b900b7f.png)

> In this case the request file was not created because the selected validation was `field`.

The CRUDController resulting from the operation may have;

`--validation=request`;
<img width="315" alt="image" src="https://user-images.githubusercontent.com/1838187/188340428-fd4baeed-e94e-4e06-8d36-f8837028c8fb.png">

`--validation=array`;
<img width="304" alt="image" src="https://user-images.githubusercontent.com/1838187/188340398-aad77ab3-03fa-4b03-b6d5-acc26fd62ab0.png">

Or empty if the `--validation=field`.

### Is it a breaking change or non-breaking change?

Yes, for DevTools. Fix here; ...

### How can we test the before & after?

```python
php artisan backpack:crud testingArg --validation=array
php artisan backpack:crud testingArray #input array
php artisan backpack:crud testingField #input field
php artisan backpack:crud testingRequest #input request
```

2022-09-05 00:56 UTC, promatik commented on composer.json
> +        "backpack/crud": "^5.3.10"
Assuming https://github.com/Laravel-Backpack/CRUD/pull/4646 will be tagged in `5.3.10`.

2022-09-05 17:34 UTC, tabacitu requested changes

2022-09-05 17:34 UTC, tabacitu commented on composer.json
> +        "backpack/crud": "^5.3.10"
```suggestion
        "backpack/crud": "^5.3.11"
```

2022-09-05 17:34 UTC, tabacitu commented on src/Console/Commands/CrudBackpackCommand.php
> +                'How would you like to enter your validation rules for the Create and Update Operations?', [
```suggestion
                'How would you like to define your validation rules, for the Create and Update operations?', [
```

2022-09-05 17:34 UTC, tabacitu commented on src/Console/Commands/CrudBackpackCommand.php
> +            $this->deleteLines(5);
NOTE. When the question is not asked (--no-interaction), it deletes too many lines.

2022-09-07 00:45 UTC, promatik commented on src/Console/Commands/CrudBackpackCommand.php
> +            $this->deleteLines(5);
Done 👌

2022-09-07 00:47 UTC, promatik commented on src/Console/Commands/CrudBackpackCommand.php
> +                ], $options[0]);
@tabacitu just to update this one, we decided to keep the interaction by default, but on the getting started guide we recommend the usage of `-n` or `--no-interaction` to create the request by default.

2022-09-08 08:51 UTC, merged