php artisan backpack:field command
Laravel-Backpack/Generators pull request #144
Opened 2022-09-07 09:53 UTC by karandatwani92

#73 
New Feature:
What I did:
Created an artisan command to create a custom field really quick (with a stub).

What happens:
Run `php artisan  backpack:field my_field` and it would copy `text` field definition and create a field with new given name.

Run `php artisan  backpack:field my_field --withAssets` and it would copy `text` field definition and append `with-assets` Stub to it.

Run `php artisan  backpack:field my_field --from=upload` and it would copy `from` field definition

2022-09-07 10:02 UTC, pxpm commented
I still think that we should have "empty field stubs" to show how the field structure is organized and the "necessary" things to make it work when building a field from scratch. 

I would only publish text field if users use `--from=text` . 

Also notice that when using `--from`, you should not be able to use `--withAssets` or any other option that would work for "empty stubs" but can break actual fields.

2022-09-08 09:26 UTC, tabacitu requested changes
Good job @karandatwani92 . Let's incorporate Pedro's feedback too. I've rephrased it here with actionable steps. Also, found a small bug.

Good job 👏👏👏

2022-09-08 09:50 UTC, pxpm commented on src/Console/Commands/FieldBackpackCommand.php
> +        return base_path("vendor/backpack/crud/src/resources/views/crud/fields/$field.blade.php");
This should be solved 100%. 

Pro pushes the packages view namespaces in the class @tabacitu mentioned. 

We should to try to match the field with the namespaces available in ViewNamespaces class.

2022-09-08 09:52 UTC, pxpm commented on src/Console/stubs/with-assets.stub
> +@endpush
Totally this is what I meant. 
I agree that `--withAssets` could be removed .
If you dont need assets you probably just need a text field and publish it with --from=text

Cheers

2022-09-08 15:27 UTC, tabacitu commented on src/Console/stubs/with-assets.stub
> +@endpush
Whoohoo

![vibing-jojo-fletcher-gif-by-cnbc-prime](https://user-images.githubusercontent.com/1032474/189162784-399e20c5-b0dc-4efd-acd3-771b58e45710.gif)

2022-09-08 15:40 UTC, promatik commented on src/Console/Commands/FieldBackpackCommand.php
> +        $this->progressBlock("Creating view <fg=blue>resources/views/vendor/backpack/crud/fields/{$name->snake('_')}.blade.php</>");
@tabacitu that is my issue 😅
The progressBlock helper uses the last 20 chars for the info message on the right, I'll fix it soon 👌

2022-09-10 16:33 UTC, karandatwani92 commented on src/Console/Commands/FieldBackpackCommand.php
> +        return base_path("vendor/backpack/crud/src/resources/views/crud/fields/$field.blade.php");
@tabacitu Done, please check.

2022-09-10 16:33 UTC, karandatwani92 commented on src/Console/stubs/with-assets.stub
> +@endpush
@tabacitu Done, please check.

2022-09-11 04:24 UTC, merged

2022-09-11 04:26 UTC, tabacitu commented
Excellent! Well done @karandatwani92 . The only change I've done was to properly indent the stub file, clean it up and add a few more comments. The easier we make it for devs to understand how things are done inside that file, the better.

2022-09-11 23:32 UTC, promatik commented on src/Console/Commands/FieldBackpackCommand.php
> +        $this->progressBlock("Creating view <fg=blue>resources/views/vendor/backpack/crud/fields/{$name->snake('_')}.blade.php</>");
https://github.com/Laravel-Backpack/CRUD/pull/4656 👌