Allow stubs to be published
Laravel-Backpack/Generators pull request #188
Opened 2023-04-04 05:48 UTC by shadowbane

## WHY

### BEFORE - What was wrong? What was happening before this PR?
Currently, we don't allow modifying stubs for controllers, models, etc. Let's say we have a requirement in our project to use custom stubs for faster development. We don't have any way to override the default stubs.
This was requested in #32 and #121

### AFTER - What is happening after this PR?
This PR allows us to publish stubs using this command:
```PHP
$ php artisan vendor:publish --provider="Backpack\Generators\GeneratorsServiceProvider" --tag=stubs
```

And when we're using the generators, it will look the file on `stubs/backpack/generators`. If the file exists, it will use user-provided stub. If not, it will use the default one.

## HOW

### How did you achieve that, in technical terms?
Added `offerPublishing()` methods on `Backpack\Generators\GeneratorsServiceProvider`

### Is it a breaking change or non-breaking change?
non-breaking changes

### How can we test the before & after?
One example is to modify default `crud-controller.stub`
To test:
- Create a crud-controller
- Publish stubs, modify `stubs/backpack/generators/crud-controller.stub`
- Create another controller. Compare the result

2023-04-04 10:00 UTC, pxpm commented on src/Console/Commands/ChartControllerBackpackCommand.php
> +        if (file_exists(base_path('stubs/backpack/generators/chart-controller.stub'))) {
Since we are repeating this condition, can we put it inside a function in the base command that accept the `$name` ('chart-controller') parameter ? 

```php
public function getStubPath($stub) {
        if (file_exists(base_path('stubs/backpack/generators/{$stub}.stub'))) {
            return base_path('stubs/backpack/generators/{$stub}.stub');
        }

        return __DIR__.'/../stubs/{$stub}.stub';
}
```

2023-04-04 10:03 UTC, pxpm commented on src/GeneratorsServiceProvider.php
> +    protected function offerPublishing(): void
I don't think we need to add a new method here. 

Just create the `boot` method add the publish configuration inside.

2023-04-04 10:04 UTC, pxpm requested changes
Hey @shadowbane thank you so much for your effort here 🙏 

This is something we can probably do yes, I've just left some comments so that we improve this a bit more 🙏 

If you don't have time/desire to do those changes let me know and I can finish this up 👍 

Cheers

2023-04-04 13:04 UTC, shadowbane commented
Hi @pxpm thanks for the comment!
Sure, I'll refactor this.

2023-04-04 13:55 UTC, shadowbane commented on src/Console/Commands/Views/PublishOrCreateViewBackpackCommand.php
>      }
This function can also be updated with:
```PHP
protected function getStub()
{
    return $this->getStubPath($this->stub);
}
```
But I need to replace the value of `$stub` property in the file that extends abstract. What do you think?

2023-04-24 12:21 UTC, pxpm commented on src/Console/Commands/Views/PublishOrCreateViewBackpackCommand.php
>      }
Hey @shadowbane sorry it took me so much time to get back here 😞 

What's the reason for needing to replace the value ? Can't we either add a flag, or make the `getStubPath()` work for the different scenarios ? 

Cheers

2023-07-17 07:57 UTC, pxpm commented
Closing in favor or #197 . 
I moved all your commits over there @shadowbane . 

Thanks again for the PR. 🙏

2023-07-17 07:57 UTC, closed without merging