Update CrudBackpackCommand.php
Laravel-Backpack/Generators pull request #205
Opened 2024-04-02 17:30 UTC by siberfxweb

## WHY

if route prefix is defined, better to get it from backpack route prefix

### BEFORE - What was wrong? What was happening before this PR?

before it was static value with "http://domain.ltd/**admin**/

### AFTER - What is happening after this PR?

now it is dynamic value with whatever being set backpack.base.route_prefix "http://domain.ltd/**defined_path**/

### How did you achieve that, in technical terms?

if route prefix is defined, better to get it from backpack route prefix

### Is it a breaking change or non-breaking change?

no

### How can we test the before & after?

you dont need to :)

2024-04-02 18:17 UTC, pxpm requested changes

2024-04-02 18:17 UTC, pxpm commented on src/Console/Commands/CrudBackpackCommand.php
> +        (!empty(config('backpack.base.route_prefix'))
Hey @siberfxweb thanks for the PR. 

Totally agree with this change. Just 2 things that I would have prefer to address in a different way: 
1 - this ternary condition became a little bit difficult to read, we should probably create a variable above like `$routePrefix = ....` and then `->append($routePrefix)`. 
2 - I think it's safer if we do `->append($routePrefix)->finish('/')` and avoid manually adding the `/`. `finish()` will take care to add the `/` if it doesn't exist and does not duplicate it in case it's already present.

If you agree with me, do you mind doing the changes ?

Cheers

2024-04-02 19:38 UTC, siberfxweb commented on src/Console/Commands/CrudBackpackCommand.php
> +        (!empty(config('backpack.base.route_prefix'))
but what if we do not use it with empty string, I mean backpack works on the root, then double slashes will be added, how do you think ?

2024-04-02 19:39 UTC, siberfxweb commented on src/Console/Commands/CrudBackpackCommand.php
> +        (!empty(config('backpack.base.route_prefix'))
btw, github for idk what reason, marked my main account as spam and no responses, even I was using pro :/ usually its me **siberfx**

2024-04-03 13:56 UTC, merged

2024-04-03 13:59 UTC, pxpm commented
Hey @siberfxweb sorry to know that :(

I recognized the name, sometimes people use different handles, one for job another for personal projects. 
It would be better if that was the case here and not a ban :(

Hope you can sort that out shortly 🙏 

Thanks for the PR, very much appreciated. 

Cheers